apiVersion: v1
kind: Service
metadata:
  name: realworld-node-service
  labels:
    app: realworld-node
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: realworld-node
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: realworld-node-deployment
spec:
  selector: 
    matchLabels: 
      app: realworld-node
  replicas: 3 # tells deployment to run 3 pods matching the template 
  template:
    metadata:
      labels:
        app: realworld-node
    spec:
      containers:
      - name: realworld-node
        image: glgelopfalcon/node-realworld:4
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    run: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    run: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo
spec:
  selector: 
    matchLabels: 
      run: mongo
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017